include ./theme.conf
enable_remote_control yes
font_family JetBrains Mono Nerd Font
font_size 12
background_opacity 0.75

# BEGIN_KITTY_THEME
# Birds Of Paradise
include current-theme.conf
# END_KITTY_THEME