#!/usr/bin/env python3
"""
album_color.py — watches for track changes, extracts dominant color
from album art, writes ~/.config/waybar/colors.css, then signals
waybar to reload its style (no restart needed).

Dependencies:
    pip install colorthief Pillow requests

Run as a background service:
    python3 ~/.config/waybar/album_color.py &

Or add to hyprland.conf:
    exec-once = python3 ~/.config/waybar/album_color.py
"""

import subprocess
import requests
import hashlib
import colorsys
import os
import time
import signal
import re
from io import BytesIO
from PIL import Image
from colorthief import ColorThief

COLORS_CSS   = os.path.expanduser("~/.config/waybar/colors.css")
CACHE_DIR    = os.path.expanduser("~/.cache/waybar/album_art")
POLL_SECONDS = 2

# Fallback palette (Catppuccin Mocha)
FALLBACK = {
    "accent":       "#cba6f7",   # mauve
    "accent_dim":   "rgba(203, 166, 247, 0.15)",
    "bloom_soft":   "rgba(203, 166, 247, 0.08)",
    "bloom_mid":    "rgba(203, 166, 247, 0.20)",
}

os.makedirs(CACHE_DIR, exist_ok=True)


def run(cmd):
    try:
        return subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode().strip()
    except subprocess.CalledProcessError:
        return None


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


def rgb_to_hex(r, g, b):
    return f"#{r:02x}{g:02x}{b:02x}"


def boost_saturation(r, g, b, sat_boost=1.4, min_brightness=0.35):
    """Make dull colors more vivid and ensure minimum brightness."""
    h, s, v = colorsys.rgb_to_hsv(r/255, g/255, b/255)
    s = min(1.0, s * sat_boost)
    v = max(min_brightness, v)
    r2, g2, b2 = colorsys.hsv_to_rgb(h, s, v)
    return int(r2*255), int(g2*255), int(b2*255)


def make_palette(r, g, b):
    """Generate a full palette from a single dominant color."""
    return {
        "accent":     rgb_to_hex(r, g, b),
        "accent_dim": f"rgba({r}, {g}, {b}, 0.15)",
        "bloom_soft": f"rgba({r}, {g}, {b}, 0.08)",
        "bloom_mid":  f"rgba({r}, {g}, {b}, 0.25)",
        "bloom_hard": f"rgba({r}, {g}, {b}, 0.45)",
        "text_tinted": f"rgba({min(r+180,255)}, {min(g+180,255)}, {min(b+180,255)}, 0.9)",
    }


def get_dominant_color(url):
    """Download album art (or load from cache), return dominant (r,g,b)."""
    cache_key = hashlib.md5(url.encode()).hexdigest()
    cache_path = os.path.join(CACHE_DIR, cache_key + ".jpg")

    if not os.path.exists(cache_path):
        if url.startswith("file://"):
            path = url[7:]
            img = Image.open(path).convert("RGB")
            img.thumbnail((150, 150))
            img.save(cache_path)
        else:
            resp = requests.get(url, timeout=5)
            img = Image.open(BytesIO(resp.content)).convert("RGB")
            img.thumbnail((150, 150))
            img.save(cache_path)

    ct = ColorThief(cache_path)
    r, g, b = ct.get_color(quality=1)
    return boost_saturation(r, g, b)


def write_css(palette, artist="", title=""):
    """Write the colors.css file that style.css imports."""
    comment = f"/* {artist} — {title} */" if artist else "/* fallback palette */"
    a   = palette['accent']
    dim = palette['accent_dim']
    mid = palette['bloom_mid']
    sft = palette['bloom_soft']
    css = f"""{comment}
/* Auto-generated by album_color.py — do not edit manually */

window#waybar {{
    box-shadow: 0 0 18px {sft}, 0 2px 8px rgba(0,0,0,0.6);
}}

#custom-music {{
    color: {a};
}}

#custom-music.playing {{
    box-shadow: 0 0 12px {mid}, 0 0 32px {sft};
    border-color: {dim};
}}

#workspaces button.active {{
    color: {a};
    background: {dim};
    box-shadow: 0 0 8px {mid};
}}

#workspaces button:hover,
#custom-btop:hover,
#custom-notion:hover,
#temperature:hover,
#backlight:hover,
#pulseaudio:hover,
#network:hover,
#battery:hover,
#clock:hover {{
    color: {a};
    box-shadow: 0 0 10px {mid};
}}
"""
    with open(COLORS_CSS, "w") as f:
        f.write(css)


def reload_waybar():
    """Signal waybar to reload CSS without restarting."""
    run(["pkill", "-SIGUSR2", "waybar"])


def get_art_url():
    url = run(["playerctl", "metadata", "mpris:artUrl"])
    if url and (url.startswith("http") or url.startswith("file://")):
        return url
    return None


def main():
    print("[album_color] started")
    last_track = None
    write_css(FALLBACK)

    while True:
        status = run(["playerctl", "status"])
        if status not in ("Playing", "Paused"):
            if last_track is not None:
                write_css(FALLBACK)
                reload_waybar()
                last_track = None
            time.sleep(POLL_SECONDS)
            continue

        track_id = run(["playerctl", "metadata", "mpris:trackid"]) or \
                   run(["playerctl", "metadata", "xesam:title"])

        if track_id == last_track:
            time.sleep(POLL_SECONDS)
            continue

        last_track = track_id
        art_url    = get_art_url()
        artist     = run(["playerctl", "metadata", "artist"]) or ""
        title      = run(["playerctl", "metadata", "title"])  or ""

        print(f"[album_color] {artist} — {title}")

        if art_url:
            try:
                r, g, b  = get_dominant_color(art_url)
                palette  = make_palette(r, g, b)
                print(f"[album_color] color → {palette['accent']}")
            except Exception as e:
                print(f"[album_color] color extract failed: {e}")
                palette = FALLBACK
        else:
            palette = FALLBACK

        write_css(palette, artist, title)
        reload_waybar()
        time.sleep(POLL_SECONDS)


if __name__ == "__main__":
    main()
