$image = /tmp/wp-preview-matugen.png
$activeBorder = rgba(73333499)
$activeBorderGrad = rgba(5a431999)
$inactiveBorder = rgba(a08c8b30)
$backgroundColor = rgba(1a1111FF)
$pinnedWindow = rgba(733334FF)
$pinnedWindowGrad = rgba(5a431977)
